# Group variables for all ELBE forest servers

# Domain configuration
domain_name: "elbe.its.dnsi"
domain_netbios_name: "ELBE"
domain_mode: "WinThreshold"  # Windows Server 2016 functional level
forest_mode: "WinThreshold"  # Windows Server 2016 functional level

# Network configuration
dns_forwarders:
  - "8.8.8.8"
  - "8.8.4.4"

# Security configuration
password_policy:
  complexity_enabled: true
  minimum_password_age: 1
  maximum_password_age: 42
  minimum_password_length: 12
  password_history_count: 24
  lockout_threshold: 5
  lockout_duration: 30
  lockout_observation_window: 30

# Windows Features to install on all servers
common_windows_features:
  - name: "PowerShell-ISE"
    state: present
  - name: "NET-Framework-45-Features"
    state: present
  - name: "RSAT-Feature-Tools"
    state: present
  - name: "RSAT-AD-Tools"
    state: present

# Firewall rules for Active Directory services
ad_firewall_rules:
  - name: "Active Directory Domain Services (Kerberos-TCP-In)"
    localport: "88"
    protocol: "TCP"
    action: "allow"
    direction: "in"
  - name: "Active Directory Domain Services (Kerberos-UDP-In)"
    localport: "88"
    protocol: "UDP"
    action: "allow"
    direction: "in"
  - name: "Active Directory Domain Services (NTP-TCP-In)"
    localport: "123"
    protocol: "TCP"
    action: "allow"
    direction: "in"
  - name: "Active Directory Domain Services (NTP-UDP-In)"
    localport: "123"
    protocol: "UDP"
    action: "allow"
    direction: "in"
  - name: "Active Directory Domain Services (RPC-TCP-In)"
    localport: "135"
    protocol: "TCP"
    action: "allow"
    direction: "in"
  - name: "Active Directory Domain Services (SMB-TCP-In)"
    localport: "445"
    protocol: "TCP"
    action: "allow"
    direction: "in"
  - name: "Active Directory Domain Services (Kerberos-Pwd-TCP-In)"
    localport: "464"
    protocol: "TCP"
    action: "allow"
    direction: "in"
  - name: "Active Directory Domain Services (Kerberos-Pwd-UDP-In)"
    localport: "464"
    protocol: "UDP"
    action: "allow"
    direction: "in"
  - name: "Active Directory Domain Services (LDAPS-TCP-In)"
    localport: "636"
    protocol: "TCP"
    action: "allow"
    direction: "in"
  - name: "Active Directory Domain Services (GC-SSL-TCP-In)"
    localport: "3269"
    protocol: "TCP"
    action: "allow"
    direction: "in"
  - name: "Active Directory Domain Services (WinRM-TCP-In)"
    localport: "5985"
    protocol: "TCP"
    action: "allow"
    direction: "in"
  - name: "Active Directory Domain Services (ADWS-TCP-In)"
    localport: "9389"
    protocol: "TCP"
    action: "allow"
    direction: "in"

# Registry settings for security hardening
security_registry_settings:
  - path: "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa"
    name: "RestrictAnonymous"
    data: 1
    type: "dword"
  - path: "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa"
    name: "RestrictAnonymousSAM"
    data: 1
    type: "dword"
  - path: "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa"
    name: "LmCompatibilityLevel"
    data: 5
    type: "dword"
  - path: "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa"
    name: "NoLMHash"
    data: 1
    type: "dword"

# Time synchronization configuration
ntp_servers:
  - "time.windows.com"
  - "pool.ntp.org"

# Logging and monitoring
event_log_size: 102400  # 100MB
audit_policy:
  - category: "Account Logon"
    setting: "Success,Failure"
  - category: "Account Management"
    setting: "Success,Failure"
  - category: "Directory Service Access"
    setting: "Success,Failure"
  - category: "Logon Events"
    setting: "Success,Failure"
  - category: "Object Access"
    setting: "Failure"
  - category: "Policy Change"
    setting: "Success,Failure"
  - category: "Privilege Use"
    setting: "Failure"
  - category: "Process Tracking"
    setting: "No Auditing"
  - category: "System Events"
    setting: "Success,Failure"