# Ansible Inventory for ELBE Infrastructure
# Generated by Terraform

[domain_controllers]
%{ for key, server in servers ~}
%{ if contains(["primary-dc", "secondary-dc"], server.role) ~}
${server.name} ansible_host=${server.private_ip} ansible_user=azureuser ansible_connection=winrm ansible_winrm_transport=basic ansible_winrm_server_cert_validation=ignore role=${server.role}
%{ endif ~}
%{ endfor ~}

[primary_dc]
%{ for key, server in servers ~}
%{ if server.role == "primary-dc" ~}
${server.name} ansible_host=${server.private_ip} ansible_user=azureuser ansible_connection=winrm ansible_winrm_transport=basic ansible_winrm_server_cert_validation=ignore
%{ endif ~}
%{ endfor ~}

[secondary_dc]
%{ for key, server in servers ~}
%{ if server.role == "secondary-dc" ~}
${server.name} ansible_host=${server.private_ip} ansible_user=azureuser ansible_connection=winrm ansible_winrm_transport=basic ansible_winrm_server_cert_validation=ignore
%{ endif ~}
%{ endfor ~}

[admin_servers]
%{ for key, server in servers ~}
%{ if server.role == "admin-server" ~}
${server.name} ansible_host=${server.private_ip} ansible_user=azureuser ansible_connection=winrm ansible_winrm_transport=basic ansible_winrm_server_cert_validation=ignore
%{ endif ~}
%{ endfor ~}

[rds_servers]
%{ for key, server in servers ~}
%{ if server.role == "rds-server" ~}
${server.name} ansible_host=${server.private_ip} ansible_user=azureuser ansible_connection=winrm ansible_winrm_transport=basic ansible_winrm_server_cert_validation=ignore
%{ endif ~}
%{ endfor ~}

[elbe_forest:children]
domain_controllers
admin_servers
rds_servers

[elbe_forest:vars]
ansible_password={{ vault_admin_password }}
domain_name=${domain_name}
domain_netbios_name=ELBE
domain_admin_user=Administrator
safe_mode_password={{ vault_safe_mode_password }}
ansible_winrm_scheme=http
ansible_port=5985